/**
 * Gemini AI image transformation service
 * Transforms user photos into hand-drawn style art with Base brand colors
 */

import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

/**
 * Transform a user photo into a hand-drawn style illustration with Base brand colors
 */
export async function transformToHandDrawn(imageBase64: string): Promise<string> {
  const prompt = [
    {
      inlineData: {
        mimeType: "image/png",
        data: imageBase64,
      },
    },
    {
      text: `Transform this photo into a simple, clean hand-drawn illustration style.
             Use the Base brand color palette:
             - Primary: Base Blue (#0000ff)
             - Black (#0a0b0d) for outlines and shadows
             - White (#ffffff) for highlights
             - Gray tones (#b1b7c3, #5b616e, #32353d) for mid-tones
             - Accent colors: Cerulean (#3c8aff), Yellow (#ffd12f), Green (#66c800)

             Style guidelines:
             - Simple, bold outlines in black
             - Minimal shading using gray tones
             - Clean, geometric shapes
             - Flat color fills, no gradients
             - Focus on the mustache if visible
             - Playful but professional aesthetic
             - Keep the composition similar to the original

             The result should look like a hand-drawn illustration or poster art,
             not a photograph. Make it fun and engaging while staying minimal and clean.`,
    },
  ];

  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-image",
    contents: prompt,
    config: {
      responseModalities: ["Image"],
      imageConfig: {
        aspectRatio: "1:1",
      },
    },
  });

  // Extract the generated image data
  if (!response.candidates || response.candidates.length === 0) {
    throw new Error("No image generated by Gemini");
  }

  const candidate = response.candidates[0];
  if (!candidate || !candidate.content || !candidate.content.parts) {
    throw new Error("Invalid response structure from Gemini");
  }

  for (const part of candidate.content.parts) {
    if (part.inlineData && part.inlineData.data) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image data in Gemini response");
}

/**
 * Convert File to base64 string
 */
export async function fileToBase64(file: File): Promise<string> {
  const buffer = await file.arrayBuffer();
  return Buffer.from(buffer).toString("base64");
}
